### ISSUE TITLE
gasnow.org Shortcut for iOS, display issue, the Rapid and Fast are mismatched 

### ISSUE THREAD

**Issue by zhangzhongnan928** [Taichi-Network/taichi-agent#1]
![IMG_0724](https://user-images.githubusercontent.com/33795543/100950105-c056a080-355f-11eb-87cd-1bcd1c6c5a2d.PNG)

**Comment by Phunk87** [comment]
Thanks for your feedback, we will review our logs first.

**Comment by zhangzhongnan928** [comment]
Solved with using the latest version from gasnow.org.
